### ISSUE TITLE
Truncated CSS 

### ISSUE THREAD

**Issue by pburtchaell** [cssnext/cssnext-loader#14] opened 2015-06-11 19:23 UTC
In Chrome, the CSS output is truncated. I assume this is an issue with the loader itself. Any pointers here?

![screen shot 2015-06-11 at 2 24 04 pm](https://cloud.githubusercontent.com/assets/3857324/8116075/8abb970e-1045-11e5-88d7-27eb04565acf.png)

**Comment by MoOx** [comment] 2015-06-12 03:57
I don't see how this loader might create this kind of issue. This one is really short and stupid https://github.com/cssnext/cssnext-loader/blob/master/index.js

I just tried to open my current app and found a long style tag. Indeed, I am getting some truncated styles BUT it's only in the chrome dev tools. It seems styles are actually being loaded completely. That said, if you double click to edit, you still got the truncated css (content after ...  is not loaded) so when you loose focus (and so the style is updated) you lose a part of the css and this is starting to affect the page. So looks like it's just a chrome issue, nothing more.

Closing for now, feel free to reopen if you provide a clear way to reproduce this with a proof that this loader is the problem.

**Closed by MoOx** 2015-06-12 03:57 UTC

**Comment by pburtchaell** [comment] 2015-06-12 04:01
So, this issue is bizarre, but it did only happen when I used the cssnext-loader. I just rewrote the same code in Less, used the less-loader (combined with style-loader, css-loader, & autoprefixer-loader), and didn't have any issues.

**Comment by pburtchaell** [comment] 2015-06-12 04:02
Perhaps it is an issue caused by style-loader and css-loader when combined with cssnext?

**Comment by MoOx** [comment] 2015-06-12 04:03
I think you are probably having another issue in you css output, completely not related to the weird chrome behavior. Could you share your css(next) input somewhere ?
